inputs:
  aws_access_key_id:
    description: ''
    required: true
  aws_secret_access_key:
    description: ''
    required: true
  aws_region:
    description: ''
    required: true
  aws_repo_name:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws_access_key_id }}
        aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ inputs.aws_repo_name }}
      shell: bash
      run: |
        IMAGE_TAG=$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
        DOCKER_BUILDKIT=1 docker build -t $ECR_REPOSITORY:latest .
        docker push $ECR_REPOSITORY:latest
